### PR TITLE
rev to the latest version of the service protocol

### PR DESCRIPTION
**Pull request by devoncarew**
- rev to the latest version of the service protocol

@alexander-doroshko, this brings in the new stepping type `Rewind`; when passed into `resume()` this should let us implement drop frame.

### CODE REVIEW

**Comment by devoncarew** [comment]
And re: `Rewind` - I'm happy to work on that later. If you do get to it though, please note that not all clients support poping stack frames off, so checking the return code from that step operation is important.

**Comment by devoncarew** [comment]
Looks like resume() is missing the new (optional) `frameIndex` param. We can hold off on landing this PR, or land and update the library later.

**Comment by alexander-doroshko** [comment]
> And re: Rewind - I'm happy to work on that later

Sounds great! :)

> We can hold off on landing this PR, or land and update the library later.

Either way looks good, let me know about your preferences.

**Comment by devoncarew** [comment]
@johnmccutchan will likely have an update to the protocol spec today - I can update this PR then.

**Comment by johnmccutchan** [comment]
Note that even on supported platforms, Rewind can and will fail for certain `frameIndex` values. Some frames are optimized and we cannot rewind to them. @turnidge can explain in detail.

**Comment by johnmccutchan** [comment]
https://codereview.chromium.org/2624493003/ <-- spec fix for frameIndex

**Comment by devoncarew** [comment]
Updated, ptal.

**Pull request merged**
