### PR TITLE
Initial breadcrumb support for Dart, WEB-33823

### PR DESCRIPTION
**Pull request by jwren**
https://youtrack.jetbrains.com/issue/WEB-33823

### CODE REVIEW

**Comment by jwren** [comment]
@alexander-doroshko 
https://youtrack.jetbrains.com/issue/WEB-33823

**Comment by alexander-doroshko** [comment]
Sorry for the delay with this PR.
Meanwhile, have you investigated whether using outline info from server is possible/ makes sense?

**Comment by jwren** [comment]
I have not looked into possibly having it supported with the Outline.  I will do so soon.

**Comment by alexander-doroshko** [comment]
I see that [people keep asking](https://github.com/flutter/flutter-intellij/issues/4103) for Flutter-aware breadcrumbs, so probably using server data is the best way to go.

**Comment by jwren** [comment]
I agree.  Closing out this PR.  I'll try to get to it soon.

**Pull request closed without merging**
