### PR TITLE
Update the Dart parser to allow triple-shift operators, and triple-shifts as a valid shift operator.

### PR DESCRIPTION
**Pull request by jwren**
The first of up to 3 parser changes: https://github.com/dart-lang/sdk/issues/44918

### CODE REVIEW

**Comment by jwren** [comment]
@alexander-doroshko

**Comment by alexander-doroshko** [comment]
Thanks! LGTM.

Could you add a test (`DartParsingTest`)? Updating an existing file would be enough (say, `Operators.dart`). Having something like `<List<List<List>>>`  in a test would be great - to make sure parser can distinguish generics vs operator. Symbol literal (`#>>>`) is also a good case for parsing test.

Also, I guess, new operator should be added to a couple of token sets in `DartTokenTypesSets`.

**Comment by jwren** [comment]
@alexander-doroshko PTAL, from my commit: Add >>> tests into DartParsingTest, and updated DartTokenTypesSets to include >>>, note that I also added >> where it was missing.

**Comment by alexander-doroshko** [comment]
Great! Thanks, merged.

**Pull request closed without merging**
