### PR TITLE
Fix WEB-24013

### PR DESCRIPTION
**Pull request by stevemessick**
@alexander-doroshko This fixes https://youtrack.jetbrains.com/issue/WEB-24013

It changes three tests to be more consistent with Java behavior. I believe you had requested that change earlier.

I added a note to one of the tests explaining that it is moving the code one line too far. I don't have time to fix that right now. I'll add an issue to the tracker.

Edit: https://youtrack.jetbrains.com/issue/WEB-24986

### CODE REVIEW

**Comment by alexander-doroshko** [comment]
I tried the example from https://youtrack.jetbrains.com/issue/WEB-24986. 
I'd expect `int i=0;` to become the last statement inside `else{}` block after moving up. It works this way in Java. In other words, `VarIfDo_afterUp.dart` should be 
```
    if (x) n(); else {
      m();
      int i=0;
    }
```

As a rule moving any statement up and down, as well as down and up should result in an untouched code. It's not the case for `int i=0;` line in this example.

**Comment by stevemessick** [comment]
You've restated the issue and added the obvious declaration of invertible
idempotency, which is implied in the issue. Do you have a question? I'm not
sure what the purpose of this comment is.

**Comment by alexander-doroshko** [comment]
Sorry for the confusion, I looked at the incorrect tab in my browser and tested this PR against WEB-24986, but should have tested against WEB-24013. Taking another look. Sorry again.

**Comment by alexander-doroshko** [comment]
Verified that it fixes the case from the 1st comment to the WEB-24013. Pushing.

**Comment by alexander-doroshko** [comment]
P.S. Got exception trying to move `foo();` up:
```
main() {
  foo();
}
```

**Pull request merged**
