### PR TITLE
Fix IDEA-98836

### PR DESCRIPTION
**Pull request by fwienber**
"Good code red when using non top-level package resource bundle"
https://youtrack.jetbrains.com/issue/IDEA-98836

To resolve package name from relative file position, reused existing
utility method JSResolveUtil.getExpectedPackageNameFromFile().

Sorry that there are no tests, but there haven't been any tests for
FlexPropertySupport before so I don't really know where to start.

### CODE REVIEW

**Comment by alexander-doroshko** [comment]
Thank you for your contribution!
Take a look at `FlexHighlightingTest.testResourceReferences2()`, you may update this test or add a similar one.

**Comment by fwienber** [comment]
Thanks for the code pointer! With all the examples of testing for green/red Flex code, it was easy to add a test (see new commit) that is red with the previous code and green with my fix.
Works for you?

**Comment by alexander-doroshko** [comment]
Yep, applying the PR now, thanks!

One question though. In the test you invoke quick fix, but it does nothing in this case. Is it needed? If not I'll remove last 3 lines of the test.

**Comment by fwienber** [comment]
Probably not, I was asking that myself, too. I copied these lines from a similar test and thought they might be needed to trigger error-checking, but if this is not the case, then they can of course be removed.

Btw., one thing that could be improved is that completion of resource bundle names does not work as I expected with my solution. Completion suggestions are correctly found for the fully-qualified name, but it would of course also be nice if you could type the non-qualified name and IDEA would complement the package (like when referencing normal classes).

**Pull request merged**
