### PR TITLE
Dart hover improvement- indent parameters in a similar manner to the Java support

### PR DESCRIPTION
**Pull request by jwren**

### CODE REVIEW

**Comment by alexander-doroshko** [comment]
Good idea!
Could you also handle nested generics? Looks like simple splitting on comma is not enough. Perhaps we need to write a custom splitter that counts angle brackets balance.
```
foo(Map<String, Map<String, String>> x) {}
bar(Map<String, Map<String, String>> x, y) {}
```
P.S. Now I don't care how many commits there are in a PR (now I have to take the whole PR as a single patch), so you don't need to force-push.

**Comment by jwren** [comment]
Yes, will do.  I'll ping again after I do so.

**Comment by jwren** [comment]
Take a look.  Nested generics now supported, test added.

**Comment by alexander-doroshko** [comment]
Thanks, merged!

**Pull request closed without merging**
