### PR TITLE
Add request listener methods to AnalysisServer interface.

### PR DESCRIPTION
**Pull request by lambdabaa**
This patch builds on the work in d6a6512b6ea0f1faee3cebd6c05271bed9369b99
which added a mechanism to subscribe to notifications whenever the Dart
analysis server client receives a response. Here we're adding the
symmetric capability for subscribers to be notified whenever a request
will be issued. This new hook allows tools interfacing with the Dart
plugin (like Flutter) to do things like measure roundtrip times to the
Dart analysis server.

Note that the upstream changes were merged in https://dart-review.googlesource.com/c/sdk/+/86583.

/cc @alexander-doroshko @jwren @scheglov

### CODE REVIEW

**Comment by alexander-doroshko** [comment]
Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.
Thanks!

**Comment by lambdabaa** [comment]
> Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it.

Done, thanks!

**Comment by lambdabaa** [comment]
Hi @alexander-doroshko. Apologies for not checking the build first! Compiling and running following the project setup instructions works for me after applying these two additional commits. Thanks!

**Comment by alexander-doroshko** [comment]
Much better! Merged!

**Comment by lambdabaa** [comment]
> Much better! Merged!

Awesome, thanks @alexander-doroshko! Would you be able to cherry pick this into the 2018.3 release?

**Comment by alexander-doroshko** [comment]
Yup!

**Pull request merged**
