### PR TITLE
IDEA-138481 support subbundles

### PR DESCRIPTION
**Pull request by brampouwelse**
- Added a configuration option to indicate that a project should be considered to be a bnd workspace
 - osmorc-jps-plugin: to use the bnd project to configure the builder (if the project is marked as a bnd workspace)
 - bnd project import: Not to add the OSGi facet (and remove it if it's already there)
 - bnd project import: For module dependencies also add the generated bundle as dependency. 
 	Not necessarily required to get subbundles to work but I needed this for some of the workspaces I've tested the changes with as with bnd it's possible add classes from the module buildpath or even from files that are not on the module buildpath to a bundle using Export-Package and Include-Resource instructions. Because of this it's possible that classes that are available in the bundle bundle jar are not available when only adding the module dependency. (Bndtools has the same "fix" for this issue).

### CODE REVIEW

**Comment by brampouwelse** [comment]
@trespasserw Did you have a chance to look at this PR? If you have any comments or ideas for a better way to get subbundles supported let me know.

**Comment by trespasserw** [comment]
Hi Bram,
Thank you for taking the time ti look into this. I have reviewed the changes, and I do not agree with some of them. I can either list my objections or implement my own solution based on your code. Which way would you prefer?

**Comment by brampouwelse** [comment]
Hi Roman, 

Thanks for reviewing my changes. I don't have a strong preference as long as we can get subbundles supported ;) I can live whatever is the easiest for you. 

If you decide to implement your own solution could you then still share your objections for me to learn from? I'm Already working on some other things I'm was used to have in Bndtools Eclipse plugin and are missing in IntelliJ.

**Comment by trespasserw** [comment]
Sorry for the late reply.

Mainly, I'm against dropping the facet. Besides the compilation, it affects inspections, and it is easier and less error prone to have a single point of configuration for a module.

Hope to have this and the other changes integrated by the end of the next week.

**Comment by brampouwelse** [comment]
No problem, let me know when you have something working I'd be happy to give it a spin and see if it works for me. 

I wasn't completely sure about dropping the facet but I'm completely new to IntelliJ so this was the easiest thing to do for me. Thinking about it again it might be nice to be able to use the facet to as an "editor" to edit the bnd.bnd file.

**Comment by brampouwelse** [comment]
Hi @trespasserw, 

Any news on this one? I'm still using a slightly changed version of what is in this PR for some project's I'm working on and that works for me. 

I did run into some `ClassNotFoundExceptions` because the `org.w3c.dom.ElementTraversal` class is not available in the `osmorc-jps-plugin` class loader. This seems to be triggered when using the new Bndtools Maven stuff like the `BndPomRepository` [1] or when you have a `~/.m2/settings.xml` (that contains connection settings).

1: http://bnd.bndtools.org/plugins/pomrepo.html

**Comment by trespasserw** [comment]
Hi Bram,

just finished working on it, the changes should appear on Github within an hour. Tested it on "amdatu-bootstrap" project, seems to work.

Do you have a stacktrace of that exception, per chance?

**Comment by brampouwelse** [comment]
Hi Roman, 

Cool will have a look at it once it's available :) 

I have a stacktrace (see below) but that originates from some point in the plugin that's probably not even in this PR as I had to adapt a bit to get it to work with other changes you did after I've created this PR. 

```
Error:Internal error: (java.lang.ClassNotFoundException) org.w3c.dom.ElementTraversal
java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.xerces.parsers.AbstractDOMParser.startDocument(Unknown Source)
	at org.apache.xerces.impl.dtd.XMLDTDValidator.startDocument(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentScannerImpl.startEntity(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.startDocumentParsing(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at aQute.bnd.connection.settings.SettingsParser.<init>(SettingsParser.java:42)
	at aQute.bnd.connection.settings.ConnectionSettings.parse(ConnectionSettings.java:301)
	at aQute.bnd.connection.settings.ConnectionSettings.readSettings(ConnectionSettings.java:55)
	at aQute.bnd.build.Workspace.setTypeSpecificPlugins(Workspace.java:616)
	at aQute.bnd.osgi.Processor.getPlugins(Processor.java:514)
	at aQute.bnd.osgi.Processor.getPlugins(Processor.java:517)
	at aQute.bnd.osgi.Processor.getPlugins(Processor.java:466)
	at aQute.bnd.build.Project.prepare(Project.java:347)
	at aQute.bnd.build.Project.getTarget(Project.java:1521)
	at aQute.bnd.build.Project.getOutputFile(Project.java:1850)
	at aQute.bnd.build.Project.getOutputFile(Project.java:1857)
	at org.jetbrains.osgi.jps.build.OsmorcBuildTarget.<init>(OsmorcBuildTarget.java:64)
	at org.jetbrains.osgi.jps.build.OsmorcBuildTargetType.computeAllTargets(OsmorcBuildTargetType.java:59)
	at org.jetbrains.jps.builders.impl.BuildTargetRegistryImpl.<init>(BuildTargetRegistryImpl.java:45)
	at org.jetbrains.jps.cmdline.BuildRunner.load(BuildRunner.java:81)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:267)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:238)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by brampouwelse** [comment]
And now I'm asking questions anyway ... one other thing I'm still not completely sure of is what is the best way to work on this plugin. 

I've tried 2 options and both seem to have issues ;) 

First I've imported the plugin into a project, and changed something in the iml to make IntelliJ recognize it as a plugin module. This works but I had to disable the test code as that refers to test code from the intellij-community project. 

Because of this I've also created a project with the full intellij-community project and added the plugin module there, this seems to compile just fine, and I had a look at some python plugin to create a "launchable module". This works but this way the module is not a plugin that I can export so the only way to use the plugin is launching IntelliJ from this project. 

Is there a better way of getting a working development environment to work on this plugin?

**Comment by brampouwelse** [comment]
Didn't get to do actual testing yet, did have a quick look at the code and found one thing that's not necessarily related to subbundles but was "fixed" in this PR as well. Created an issue for that [1]

1: https://youtrack.jetbrains.com/issue/IDEA-167171

**Comment by trespasserw** [comment]
Thanks for the stacktrace. I have fixed the cause in the platform; as a workaround, you may add `xml-apis.jar` from the platform to `compileServer.plugin@classpath` attribute.

About IDEA-167171 - I deliberately omitted that part of the commit. It fixes a problem by adding a dependency on an artifact of a compilation - it means that code analysis in IDEA won't work until a project is compiled.
In case of "amdatu-web" project, a correct solution would be marking "javax.ws.rs.jsr311-api" as an exported dependency of "org.amdatu.web.rest" module. I'm yet to find out how to handle these cases automatically.

True, at the moment there is no convenient way to work on the plugin :( I'll try to create a Gradle project for it, for start.

**Comment by brampouwelse** [comment]
> Thanks for the stacktrace. I have fixed the cause in the platform; as a workaround, you may add xml-apis.jar from the platform to compileServer.plugin@classpath attribute.

Cool, thanks! Guess that I can simply pull the latest version of the platform from the intellij-community version as I'm currently running the plugin from a project with both intellij-community and the plugin. 

> About IDEA-167171 - I deliberately omitted that part of the commit. It fixes a problem by adding a dependency on an artifact of a compilation - it means that code analysis in IDEA won't work until a project is compiled.
In case of "amdatu-web" project, a correct solution would be marking "javax.ws.rs.jsr311-api" as an exported dependency of "org.amdatu.web.rest" module. I'm yet to find out how to handle these cases automatically.

In this case that could work but that would be a lot harder when resources are added by an `Include-Resource` header as that can include classes that are not even on the build path of the module. And another issue could be that you get all contents of the jar that's marked as an exported dependency instead of only the packages that are actually included in the bundle. Is it possible to export a subset of packages from a dependency? 

> True, at the moment there is no convenient way to work on the plugin :( I'll try to create a Gradle project for it, for start.

Ok, at least nice to hear that I'm not over complicating something that should be easy

**Comment by tkaven** [comment]
i find a big bug in jetBrains vue plugins:
in <Row></Row> can not ins enter, can not ins comma, and can not comment with shortcut key

**Comment by anstarovoyt** [comment]
Hi! I am closing the PR since there are no activities from 2017 year, and there are merge conflicts. If you still interested in the changes please create a new PR. 

Thank you for your contribution to the IntelliJ plugins!

**Pull request closed without merging**
