### PR TITLE
Add ngx-kit to ng-packages.json

### PR DESCRIPTION
**Pull request by navix**

### CODE REVIEW

**Comment by piotrtomiak** [comment]
@navix - Thank you for your contribution! Could sign and send us Contributor Agreement? See https://www.jetbrains.com/agreements/cla/

**Comment by navix** [comment]
@piotrtomiak Done. Do you need some additional confirmation?

**Comment by piotrtomiak** [comment]
@navix - thank you, I am waiting for confirmation from the legal team. I'll merge PR once I get it.

**Comment by piotrtomiak** [comment]
Changes have been merged manually, thank you for the contribution!

**Comment by navix** [comment]
@piotrtomiak Thanks!

**Pull request closed without merging**
