### PR TITLE
Add spellchecker for Dart string literals

### PR DESCRIPTION
**Pull request by solid-software**
Fixes https://youtrack.jetbrains.com/issue/WEB-34709

### CODE REVIEW

**Comment by alexander-doroshko** [comment]
@solid-software Have you submitted a contributor license agreement? If not, please follow the steps described at http://www.jetbrains.com/agreements/cla/ to sign it. Thanks!

**Comment by solid-software** [comment]
@alexander-doroshko done! Thanks for quick reply!

**Comment by alexander-doroshko** [comment]
Please update `DartHighlightingTest#testSpelling` (which effectively means updating `Spelling.dart` file) to test the added functionality.

Also, we need your real name and family name in the signed CLA, not the company name.

**Comment by solid-software** [comment]
@alexander-doroshko please review. CLA updated as well.

**Comment by alexander-doroshko** [comment]
Thanks, lgtm. Will merge shortly.

**Comment by solid-software** [comment]
Hi @alexander-doroshko, any updates on merging this PR?

**Comment by bootstraponline** [comment]
@alexander-doroshko this update would be helpful for us at Robinhood. 🙂

**Comment by alexander-doroshko** [comment]
I'm awfully sorry for the delay.

Unfortunately, the PR doesn't compile. Dart plugin can't access classes specific for Java support because Dart plugin can also work in WebStorm, PyCharm and other IDEs that don't have Java support at all. Current implementation of `DartStringLiteralTokenizer` uses 3 Java-specific classes: `AnnotationUtil`, `PsiModifierListOwner`, and `PsiLiteralExpressionImpl`. You'll get the compilation errors if you setup IntelliJ Community + Dart plugin from sources as described in the [README](https://github.com/JetBrains/intellij-plugins/tree/master/Dart).

**Comment by solid-software** [comment]
@alexander-doroshko could you please check it now?

**Comment by alexander-doroshko** [comment]
Thanks, it works now.
I've noticed 2 corner cases: `\uXXXX` escape sequence and string interpolations (vars used in interpolations shouldn't be checked, they are already checked where they are declared).
image

**Comment by solid-software** [comment]
@alexander-doroshko please review changes for escape sequences and string interpolations support

**Comment by solid-software** [comment]
Hi @alexander-doroshko - any updates on this?

**Comment by alexander-doroshko** [comment]
In progress.

**Comment by alexander-doroshko** [comment]
Thank you very much for the pull request! I've merged it with some simplifications. The link to the commit will appear here shortly. I'm sorry it took quite a while.

In particular, I simplified interpolations handing by consuming `DartTokenTypes.REGULAR_STRING_PART` instead of `DartStringLiteralExpression`.

As for escape sequences, I found that we already have `DartAnnotator.getEscapeSequenceRangesAndValidity()` method and reused it.

**Comment by solid-software** [comment]
Great - thanks @alexander-doroshko, happy to see it working now!

**Pull request closed without merging**
