### PR TITLE
Dart: Add Shebang Detection

### PR DESCRIPTION
**Pull request by kaendfinger**
This adds shebang detection for Dart.

### CODE REVIEW

**Comment by alexander-doroshko** [comment]
Sorry I didn't notice the pull request earlier. It is recommended to file an issue in YouTrack together with the pull request, so everybody will be able to track the issue status and finally it will go to the release notes.
Unfortunately I have to reject this pull request. FileTypeIdentifiableByVirtualFile#isMyFileType must work instantly, it is called millions of times! And loading a file is an extremely costly operation.
By the way what is the use case for the problem you are trying to solve? Will it be enough for you to add your project-specific file names (or patterns) to the Settings (Preferences) | Editor | File Types | Dart?

**Comment by kaendfinger** [comment]
Would I not have to add a file specific file name for every single script I have without a .dart extension? This is the problem I am trying to solve. I wish I could make this faster :(

**Comment by nicity** [comment]
You can implement DartFileTypeDetector, similar to e.g.
GroovyHashBangFileTypeDetector

On Tue, Mar 17, 2015 at 8:10 PM, Kenneth Endfinger <notifications@github.com

**Comment by kaendfinger** [comment]
Ok

**Pull request closed without merging**
