### PR TITLE
Implement WEB-39577- folding of DartAssertStatements

### PR DESCRIPTION
**Pull request by jwren**
https://youtrack.jetbrains.com/issue/WEB-39577

### CODE REVIEW

**Comment by alexander-doroshko** [comment]
Just curious, is it just to behave similarly to foldings produced by Analysis Server? Do people write lots of multi-line asserts where they could benefit from folding?

**Comment by jwren** [comment]
Yes, a user reached out after having to review & read through an assert that was 20 lines.

**Comment by devoncarew** [comment]
Multi-line asserts are a common pattern in the Flutter framework code:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/scaffold.dart#L1553

**Comment by alexander-doroshko** [comment]
@jwren @devoncarew What about folding only multiline asserts but keep single-line untouched? This is how we handle map/set literals, for example.

**Comment by devoncarew** [comment]
👍 sounds reasonable to me

**Comment by jwren** [comment]
SGTM, I'll take a look today.

**Comment by jwren** [comment]
Nevermind, you took care of it already with https://github.com/JetBrains/intellij-plugins/commit/7da3d957f7b0b58970ad2d38ae1618410e58d7cf 

Thanks Alex

**Pull request closed without merging**
