### PR TITLE
IDEA-137625 Add support for language injection in Cucumber plugin

### PR DESCRIPTION
**Pull request by danic-wd**
Adds supports for injecting XML/JSON/YAML in Gherkin docstrings. See https://youtrack.jetbrains.com/issue/IDEA-137625 for details of the feature request

### CODE REVIEW

**Comment by danic-wd** [comment]
Merged here: https://github.com/JetBrains/intellij-plugins/commit/79e5186d66531db1cce3d06aa6ac5bb64b2670e9
Closing

**Comment by danic-wd** [comment]
Merged: https://github.com/JetBrains/intellij-plugins/commit/79e5186d66531db1cce3d06aa6ac5bb64b2670e9

**Comment by dkarlovi** [comment]
@danic-wd was this released yet? It doesn't seem to work for me.

**Comment by danic-wd** [comment]
> @danic-wd was this released yet? It doesn't seem to work for me.

It took a few months, was eventually released but it was broken. Now you need to wait for this other fix to be released by the looks of things:

https://youtrack.jetbrains.com/issue/IDEA-251322

**Comment by dkarlovi** [comment]
Oh, it's no rush, was just wondering if I need to do something to get it working, no issue to just wait. Thanks for working on this and for this fast response! :beers:

**Pull request closed without merging**
