### PR TITLE
Work on moving comments

### PR DESCRIPTION
**Pull request by stevemessick**
@alexander-doroshko Incremental improvement to Move Statement.

### CODE REVIEW

**Comment by alexander-doroshko** [comment]
Hm, I'm afraid I do not agree with test data. See my comment and sample code in it: https://github.com/JetBrains/intellij-plugins/pull/386#issuecomment-228153133
See how similar things work in Java: comment and declaration behind it are moved a a whole.

**Comment by alexander-doroshko** [comment]
Trying to move `var y;` down leads to exception
```
class Foo {
  var y;
  /*
   * doc
   */
  var x;
}
```

**Comment by stevemessick** [comment]
Fair enough. My concern for this work is to identify comment blocks. Attaching them to declarations comes later.

**Comment by alexander-doroshko** [comment]
Ok, then I suggest to integrate this pull request later together with the upcoming update.

Consequent single-line comments (both // and ///) should be treated as a block as well.

General suggestion: it seems to be more accurate to look at PsiElement.getNote().getElementType() instead of comparing PsiElement.getText() with string.

**Comment by stevemessick** [comment]
On Thu, Jun 30, 2016 at 8:07 AM, Alexander Doroshko <
notifications@github.com> wrote:

> Ok, then I suggest to integrate this pull request later together with the
> upcoming update.
>
Is this the highest-priority task? Moving comments as a single block
instead of individual lines is already a huge usability improvement. I
thought moving statements into/out of blocks would be more important than
attaching comments to declarations.

> Consequent single-line comments (both // and ///) should be treated as a
> block as well.
>
I agree, but I haven't wanted to think about that yet.

> General suggestion: it seems to be more accurate to look at
> PsiElement.getNote().getElementType() instead of comparing
> PsiElement.getText() with string.
>
I thought you said to not fetch the AST if everything needed was in the PSI
nodes? I'd prefer to use getElementType() but I had been avoiding it
because of some earlier comment.

**Comment by alexander-doroshko** [comment]
I'd rate comment+declaration handling as a must have for component mover feature.

> I thought you said to not fetch the AST if everything needed was in the PSI
nodes?

Yes, I said that checking `instanceof` for `PsiElement` is better than checking its `ASTNode.getElementType()`. But checking AST element type is better than using `PsiElement.getText()` :-).

**Pull request closed without merging**
