### PR TITLE
Ignore TODOs from the Dart Analysis Server in the new Dart Analysis panel, like the previous panel

### PR DESCRIPTION
**Pull request by jwren**
…

### CODE REVIEW

**Comment by alexander-doroshko** [comment]
Pushed, thanks. Next time please reformat added code. You can call reformat action manually or enable corresponding check box in the Commit dialog.

**Comment by jwren** [comment]
Sorry!, Yes of course.

**Comment by alexander-doroshko** [comment]
I noticed that I've accidentally removed similar check in DartServerErrorsAnnotator few months ago and currently all TODOs are highlighted as warnings. I think we have thousands of users and nobody reported... :). Pushing the fix.

**Comment by jwren** [comment]
Maybe they have no TODOs   :)   Thanks for pushing a fix.

**Pull request merged**
