### PR TITLE
add missing keywords  & fix subexpr

### PR DESCRIPTION
**Pull request by patricklx**
add null & undefined keywords : https://handlebarsjs.com/guide/expressions.html#literal-segments

also fixes some subexpressions issues
fixes
* https://youtrack.jetbrains.com/issue/WEB-27865/Handlebars-syntax-support-missing-parenthesis-support
* https://youtrack.jetbrains.com/issue/WEB-57591/handlebars-parenthesis-inside-curly-fails-parsing-Expected-a-path-String-Number-Boolean-or-data

### CODE REVIEW

**Comment by anstarovoyt** [comment]
@patricklx hello! Thank you for the contribution. Could you please add some tests?

**Comment by patricklx** [comment]
@anstarovoyt 👍 done

**Comment by patricklx** [comment]
@anstarovoyt all tests are passing now

**Comment by patricklx** [comment]
Hi @anstarovoyt. Anything else that needs to be done?

**Comment by patricklx** [comment]
Hi @anstarovoyt., any news?

**Comment by anstarovoyt** [comment]
Hello, I am in process of review, I hope I will finish it next week.

**Comment by anstarovoyt** [comment]
@patricklx Hello, I finally reviewed the changes; we have a tricky merging process, so the pull request will be merged indirectly in several hours.
 Why the PR in general is ok, I still have some questions:
1. I noticed unused "Null" / "Undefined" psi elements, most likely they can be removed. 
2. parseMustache tries to parse `parseSexpr` twice; I am not sure that it is expected behavior (moreover, the return value isn't used at all). I think the "else" block can be removed.

**Comment by patricklx** [comment]
The Null and Undefined psi elements are there so that they can be correctly highlighted just like Boolean psi element.
Your talking about line 463? Your are right, i didn't notice when refactoring. The else can be removed.

**Pull request closed without merging**
