### PR TITLE
Add Dart quick fix actions on the selected Dart Problem in the Dart Analysis panel

### PR DESCRIPTION
**Pull request by jwren**

### CODE REVIEW

**Comment by alexander-doroshko** [comment]
LGTM!

Maybe add a standard 'Quick Fix' icon to the actions?

Also, I think it makes sense to open the file at the corresponding offset before invoking a quick fix. Otherwise, nothing visible happens on menu item click.

**Comment by jwren** [comment]
Icon: Yes, I looked for the icons and the logic to map between errors | warnings | hints to the appropriate AllIcons.icon, but could not find it.  Point me to the icons and I'll update the PR.

Open file- Good point.  I'll update the PR.

**Comment by alexander-doroshko** [comment]
I mean `AllIcons.Actions#QuickfixBulb`, will it look good for the action?

**Comment by jwren** [comment]
Closing pull request, PR now at https://github.com/JetBrains/intellij-plugins/pull/581

**Pull request closed without merging**
