### PR TITLE
Dart plugin NPE fix, check for a null from the parent.getTextRange() call

### PR DESCRIPTION
**Pull request by jwren**
@alexander-doroshko I've seen a dozen or so such NPE stack traces in the past week

### CODE REVIEW

**Comment by alexander-doroshko** [comment]
@jwren any chance to reproduce? This might be caused by incorrect parsing (no reference parsed where expected). As a result, the search results presentation might be not great (even with this fix). I'll merge this PR but still very curious about the code sample.

**Comment by jwren** [comment]
I attempted, but failed to get a code sample.  I am curious too.  We could log with the PSI structure that lead up to the `null`.

**Comment by alexander-doroshko** [comment]
Do you have full stack traces? I'm curious, whether the previous stack frame is always the same or it can be both `DartServerFindUsagesHandler` and `DartRenameDialog`.

**Comment by jwren** [comment]
stack trace:

```

{
  frames: [{
    class_name: "com.jetbrains.lang.dart.ide.findUsages.DartServerFindUsagesHandler",
    method_name: "getUsagePsiElement",
    filename: "DartServerFindUsagesHandler.java",
    line_number: 131
  },{
    class_name: "com.jetbrains.lang.dart.ide.findUsages.DartServerFindUsagesHandler$1",
    method_name: "consumeInReadAction",
    filename: "DartServerFindUsagesHandler.java",
    line_number: 84
  },{
    class_name: "com.jetbrains.lang.dart.ide.findUsages.DartServerFindUsagesHandler$1",
    method_name: "consumeInReadAction",
    filename: "DartServerFindUsagesHandler.java",
    line_number: 65
  },{
    class_name: "com.jetbrains.lang.dart.ide.findUsages.ReadActionConsumer",
    method_name: "lambda$consume$0",
    filename: "ReadActionConsumer.java",
    line_number: 25
  },{
    class_name: "com.intellij.openapi.application.impl.ApplicationImpl",
    method_name: "runReadAction",
    filename: "ApplicationImpl.java",
    line_number: 948
  },{
    class_name: "com.jetbrains.lang.dart.ide.findUsages.ReadActionConsumer",
    method_name: "consume",
    filename: "ReadActionConsumer.java",
    line_number: 25
  },{
    class_name: "com.jetbrains.lang.dart.analyzer.DartAnalysisServerService",
    method_name: "search_findElementReferences",
    filename: "DartAnalysisServerService.java",
    line_number: 1266
  },{
    class_name: "com.jetbrains.lang.dart.ide.findUsages.DartServerFindUsagesHandler",
    method_name: "processElementUsages",
    filename: "DartServerFindUsagesHandler.java",
    line_number: 98
...
```

**Pull request closed without merging**
