### PR TITLE
Create a new component template

### PR DESCRIPTION
**Pull request by talkid134**
It's a helpful improvement for ts-users.

### CODE REVIEW

**Comment by talkid134** [comment]
i've signed in now

**Comment by alexander-doroshko** [comment]
Could you attach a screenshot showing what this pull request adds to the IDE? I applied the pull request locally but I don't see any visible effect.

**Comment by talkid134** [comment]
i could not check results, can you compile it and say me what's going on?

**Comment by alexander-doroshko** [comment]
> I could not check the results

Why?

**Comment by talkid134** [comment]
I just copy-pasted files with some changes. If It is requred I can check it on my machine.

**Comment by alexander-doroshko** [comment]
Of course, contributors must submit fully tested contributions. And in most cases (but not in this one) pull request should include a written test for the added functionality.

**Comment by alexander-doroshko** [comment]
We decided that one Vue file template is enough by default, just not to add extra clutter to the New File menu. For those who need different templates it's super easy to edit the predefined ones and/or to add custom ones (File and Code Templates page in Settings).

**Pull request closed without merging**
