### PR TITLE
update the dart icons

### PR DESCRIPTION
**Pull request by devoncarew**
Based on the new Dart icon:

dart_192

@alexander-doroshko @jwren

### CODE REVIEW

**Comment by jwren** [comment]
LGTM

**Comment by alexander-doroshko** [comment]
Is this new icon finalized? What is the 'official' source of icons like this? Previously I thought it was https://github.com/dart-lang/logos but it seems to be out-of-date.
Our process requires involving our design team when we need to change icons. I'll ask them, no actions needed from you. Just wanted to make sure that the new icon is here for a long time.

**Comment by devoncarew** [comment]
This is the new icon for Dart - updated to better match Material guidelines. You can see it on the dartlang.org website now (and the logos site update is in progress: https://github.com/dart-lang/logos/pull/4).

**Comment by alexander-doroshko** [comment]
Thanks, I'll take care of this.

**Comment by qingweiSun** [comment]
.dart  icon  ?

**Pull request closed without merging**
