### PR TITLE
DartDocumentationProvider fix: NPE prevention from a PsiElement.getContainingFile() call.

### PR DESCRIPTION
**Pull request by jwren**

### CODE REVIEW

**Comment by alexander-doroshko** [comment]
@jwren, do you know real use cases when NPE happens here? Normally we don't check `PsiElement.getContainingFile()` for null, instead clients are responsible for passing valid PsiElements.

**Comment by jwren** [comment]
No, I could not reproduce the issue myself, I did get a number (hundreds) of reports of this issue however.

**Comment by alexander-doroshko** [comment]
Who have you received the reports from? Please send me full stack trace by email. Full logs and any other details will help.

**Comment by devoncarew** [comment]
@jwren, is this will an issue?

**Comment by jwren** [comment]
This is still an issue, but I still don't have a repro.  As Alex pointed out this change shouldn't be needed, and is not a best practice in IntelliJ.

Here is an example of a stack trace below.  I will try to figure out a repro and follow up with a different CL or email.

{
  frames: [{
    class_name: "com.jetbrains.lang.dart.analyzer.DartAnalysisServerService",
    method_name: "$$$reportNull$$$0",
    filename: "DartAnalysisServerService.java",
    line_number: -1
  },{
    class_name: "com.jetbrains.lang.dart.analyzer.DartAnalysisServerService",
    method_name: "analysis_getHover",
    filename: "DartAnalysisServerService.java",
    line_number: -1
  },{
    class_name: "com.jetbrains.lang.dart.ide.documentation.DartDocumentationProvider",
    method_name: "getSingleHover",
    filename: "DartDocumentationProvider.java",
    line_number: 128
  },{
    class_name: "com.jetbrains.lang.dart.ide.documentation.DartDocumentationProvider",
    method_name: "getSingleHover",
    filename: "DartDocumentationProvider.java",
    line_number: 200
  },{
    class_name: "com.jetbrains.lang.dart.ide.documentation.DartDocumentationProvider",
    method_name: "generateDoc",
    filename: "DartDocumentationProvider.java",
    line_number: 45
  },{
    class_name: "com.intellij.lang.documentation.CompositeDocumentationProvider",
    method_name: "generateDoc",
    filename: "CompositeDocumentationProvider.java",
    line_number: 136
  },{
    class_name: "com.intellij.codeInsight.documentation.DocumentationManager$MyCollector",
    method_name: "lambda$getDocumentation$2",
    filename: "DocumentationManager.java",
    line_number: 1139
  },{
    class_name: "com.intellij.openapi.application.impl.ApplicationImpl",
    method_name: "tryRunReadAction",
    filename: "ApplicationImpl.java",
    line_number: 1168
  },{
    class_name: "com.intellij.openapi.progress.util.ProgressIndicatorUtils",
    method_name: "lambda$runInReadActionWithWriteActionPriority$0",
    filename: "ProgressIndicatorUtils.java",
    line_number: 70
  },{
    class_name: "com.intellij.openapi.progress.util.ProgressIndicatorUtils",
    method_name: "lambda$runWithWriteActionPriority$1",
    filename: "ProgressIndicatorUtils.java",
    line_number: 123
  },{
    class_name: "com.intellij.openapi.progress.impl.CoreProgressManager",
    method_name: "lambda$runProcess$2",
    filename: "CoreProgressManager.java",
    line_number: 164
  },{

**Comment by alexander-doroshko** [comment]
@jwren Thanks for the stack trace, the problem is much more clear now!

It is `PsiFile.getVirtualFile()` that returns `null`. According to its javadoc, it's expected in some cases. I already added the [required 'if'](https://github.com/JetBrains/intellij-plugins/commit/f5eb8fe523ff65f61b23701a2e3dc3d3b6f813ec#diff-35900d987289a83af101d18a9f7c3501) recently.

This PR checks for `PsiElement.getContainingFile()` for returning `null`. And this would be really unexpected in this context. That's why I wasn't sure about merging it.

**Comment by jwren** [comment]
Thank you @alexander-doroshko !

**Pull request closed without merging**
