### PR TITLE
Fix for WEB-39449, Dart problem "Documentation" tooltip text not clickable from Dart problem panel.

### PR DESCRIPTION
**Pull request by jwren**

### CODE REVIEW

**Comment by alexander-doroshko** [comment]
Thanks, merged! I only added a separator, an icon, and an action description, if you don't mind:
image

**Comment by devoncarew** [comment]
`Documentation` ==> `View Documentation`? Or, `View Documentation...`?

**Comment by jwren** [comment]
Thanks Alex!

**Comment by alexander-doroshko** [comment]
> `Documentation` ==> `View Documentation`? Or, `View Documentation...`?

Or `Open Documentation`? Or `Show Documentation`? :)

P.S. I think ellipsis not needed as we don't show any dialog but do immediately show docs.

**Comment by alexander-doroshko** [comment]
My bet is `Open Documentation`.

**Comment by alexander-doroshko** [comment]
Description (see status bar): `Open detailed problem description in browser` - could this be better?

**Comment by devoncarew** [comment]
> My bet is `Open Documentation`.

👍

**Pull request closed without merging**
