### PR TITLE
[Cucumber] Add run line contributors

### PR DESCRIPTION
**Pull request by Hunsu**

### CODE REVIEW

**Comment by Hunsu** [comment]
Hi,
Can someone take a look at this PR please ?

**Comment by misa** [comment]
Is there any progress?

**Comment by Hunsu** [comment]
@misa The code was merged by JetBrains a while ago and it was included in the version 2020.2. I don't know their process to sync with Github.

**Comment by anstarovoyt** [comment]
merged some time ago

**Pull request closed without merging**
