### PR TITLE
Change no-problems message in Dart Problems view, for @sethladd

### PR DESCRIPTION
**Pull request by jwren**

### CODE REVIEW

**Comment by sethladd** [comment]
:+1:

**Comment by alexander-doroshko** [comment]
:)
At first the message is shown for everyone for a pretty long time while analysis is in progress. I'm afraid there are users who wouldn't like the teaser before getting thousands of errors. I think we can set initial text to 'No problems found in Dart code yet' and if analysis is really done without errors - '...Happy day!'. Though when we implement filters to hide errors/warning/hints, the fact that user applied filters not always makes his day happy :)

**Comment by jwren** [comment]
I don't have a preference, and don't disagree, but being playful is fun too.

**Comment by sethladd** [comment]
Playful is good. (see: inbox when you have inbox zero :)

Agree that you don't want to show "Happy day" until analysis is complete. But when it's complete and there are no issues, say "Happy day!"

**Comment by alexander-doroshko** [comment]
> when it's complete and there are no issues, say "Happy day!"
No objections here.
Though when we implement filters and View will be without errors&warnings because user simply filtered them out - do not show 'happy day' as well.

**Pull request closed without merging**
