### PR TITLE
WEB-38172 update build gradle

### PR DESCRIPTION
**Pull request by CSchulz**

### CODE REVIEW

**Comment by piotrtomiak** [comment]
@cyberspaceru Have you signed our contributors agreement already? If you haven't, could you please go to https://www.jetbrains.com/agreements/cla/ and sign it electronically?

**Comment by CSchulz** [comment]
@piotrtomiak I just signed it.

**Comment by piotrtomiak** [comment]
@CSchulz Thank you! Your commit has been merged as `f44e4023917d21e4c24705024411dd717dcd9757`. I've modified it slightly by adding `.gitignore` and one more dependency for the plugin to compile cleanly.

**Comment by CSchulz** [comment]
Where can I find the commit?

**Comment by piotrtomiak** [comment]
@CSchulz - it'll take some time to mirror internal repo to the public one. I am not sure at what intervals it's being mirrored. I will also cherrypick your commit to `master`.

**Comment by CSchulz** [comment]
Oh ... I thought this repository is your working one.

**Pull request closed without merging**
