### PR TITLE
WEB-40331 Dart 'test' and 'group' argument folding for package:test support

### PR DESCRIPTION
**Pull request by jwren**

### CODE REVIEW

**Comment by lookfirst** [comment]
I ❤️ you @jwren

**Comment by alexander-doroshko** [comment]
LGTM.
One thought: do we want test/group name to stay visible even when the implementation is folded? For example, we could fold only the second argument of a test()/group() call. Or include test/group name in placeholder text.

**Comment by alexander-doroshko** [comment]
@jwren, WDYT about folding the 2nd argument only thus keeping the name visible (+fold only multiline implementations)?

**Comment by jwren** [comment]
See line 395 in `DartFoldingBuilder.java`- this is already implemented.  Line 399 has the logic for only multi-line implementations.

LMK if I need to rebase the PR to master to make it easier to land.

**Comment by alexander-doroshko** [comment]
Oops, my bad, I didn't notice the update. Sorry for such a delay. Merged.

**Pull request closed without merging**
