### PR TITLE
Add hook to allow subscribing for debug logs from analysis server

### PR DESCRIPTION
**Pull request by lambdabaa**
/cc @alexander-doroshko @scheglov

### CODE REVIEW

**Comment by lambdabaa** [comment]
Update: Working to have this handle analysis server restarts.

**Comment by alexander-doroshko** [comment]
There's already a universal `DartAnalysisServeService.sendRequest()` method, which is already used in `FlutterDartAnalysisServer.sendSubscriptions()`. Maybe that's enough for now?

**Comment by lambdabaa** [comment]
> There's already a universal `DartAnalysisServeService.sendRequest()` method, which is already used in `FlutterDartAnalysisServer.sendSubscriptions()`. Maybe that's enough for now?

I think that could work if we didn't also need to make sure that we subscribe to this additional topic after analysis server restart. Please see my updated changes.

**Comment by alexander-doroshko** [comment]
Thanks, merged. I've added a parameter to `setServerLogSubscription(boolean subscribeToLog)`, just to have more universal API.

**Pull request closed without merging**
