### PR TITLE
Parse operators as method declarations.

### PR DESCRIPTION
**Pull request by scheglov**
This makes operators display in the Structure view.
Also, because it is a `DartComponent` now it can be used as a resolution / navigation target in the future.

In `Dart Analysis Server` we already parse operators as methods.

### CODE REVIEW

**Comment by alexander-doroshko** [comment]
Cool!
I could easily make 'Override operator' action working (`Ctrl+O`):
image

**Comment by alexander-doroshko** [comment]
Also we've got line markers for operators for free! I've added corresponding tests.
image

**Comment by scheglov** [comment]
Nice :-)

**Comment by jwren** [comment]
Very nice, good job you two.

**Comment by alexander-doroshko** [comment]
Fixed Go To Super / Go To Implementations for operators as well + tests. It was easy now!

**Pull request merged**
