### PR TITLE
Allow handlebars language to be injected

### PR DESCRIPTION
**Pull request by dwickern**
Implementing the `InjectableLanguage` marker trait means that handlebars templates can be injected into a javascript template string using the "Inject language or reference" option.

This is particularly useful for ember-cli:
https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile

screen shot 2016-12-07 at 2 29 12 pm

### CODE REVIEW

**Comment by dwickern** [comment]
@denofevil I tested some more in response to https://twitter.com/en_Dal/status/806787420918120449

If I type some html, then I lose handlebars highlighting and get html highlighting instead. That is acceptable I think.

screen shot 2016-12-08 at 8 47 26 am

I was able to create an exception by mashing out a sequence of `{{{{{{{{{{{{{{{{{{{`. It looks like just a missing localization string:
```
'hb.parsing.element.expected.end_raw_block' is not found in java.util.PropertyResourceBundle@6f5e5f09
java.lang.AssertionError: 'hb.parsing.element.expected.end_raw_block' is not found in java.util.PropertyResourceBundle@6f5e5f09
	at com.intellij.BundleBase.messageOrDefault(BundleBase.java:51)
	at com.intellij.BundleBase.message(BundleBase.java:72)
	at com.intellij.CommonBundle.message(CommonBundle.java:64)
	at com.dmarcotte.handlebars.HbBundle.message(HbBundle.java:15)
	at com.dmarcotte.handlebars.parsing.HbElementType.parseExpectedMessage(HbElementType.java:27)
	at com.dmarcotte.handlebars.parsing.HbParsing.recordLeafTokenError(HbParsing.java:1009)
	at com.dmarcotte.handlebars.parsing.HbParsing.parseLeafToken(HbParsing.java:975)
	at com.dmarcotte.handlebars.parsing.HbParsing.parseCloseRawBlock(HbParsing.java:424)
	at com.dmarcotte.handlebars.parsing.HbParsing.parseStatement(HbParsing.java:218)
	at com.dmarcotte.handlebars.parsing.HbParsing.parseStatements(HbParsing.java:103)
	at com.dmarcotte.handlebars.parsing.HbParsing.parseProgram(HbParsing.java:88)
	at com.dmarcotte.handlebars.parsing.HbParsing.parseRoot(HbParsing.java:78)
	at com.dmarcotte.handlebars.parsing.HbParsing.parse(HbParsing.java:47)
	at com.dmarcotte.handlebars.parsing.HbParser.parse(HbParser.java:15)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:85)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.f(LazyParseableElement.java:172)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:784)
	at com.intellij.psi.impl.source.tree.injected.MultiHostRegistrarImpl.a(MultiHostRegistrarImpl.java:346)
	at com.intellij.psi.impl.source.tree.injected.MultiHostRegistrarImpl.doneInjecting(MultiHostRegistrarImpl.java:226)
	at org.intellij.plugins.intelliLang.inject.InjectorUtils.registerInjection(InjectorUtils.java:112)
	at org.intellij.plugins.intelliLang.inject.TemporaryPlacesInjector.getLanguagesToInject(TemporaryPlacesInjector.java:62)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider$MyInjProcessor.process(InjectedPsiCachedValueProvider.java:82)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:474)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider.doCompute(InjectedPsiCachedValueProvider.java:62)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.a(InjectedLanguageUtil.java:316)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:145)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass$2.process(InjectedGeneralHighlightingPass.java:191)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass$2.process(InjectedGeneralHighlightingPass.java:186)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by denofevil** [comment]
Yes, that seems unrelated, but thanks for fixing it too.
If you're fine with this pretty unstable behaviour, I think I can merge this. 
I'll try to revisit injecting template languages once again, but it seems it won't be an bulk update that will enable it for everyone, rather a one-by-one language enabling. Handlebars look ok, as they don't rely on file view provider too much (unlike JSP or ERB)

**Comment by Turbo87** [comment]
@denofevil as an example for where this is commonly used in Ember.js: https://github.com/skylines-project/skylines/blob/master/ember/tests/integration/components/flight-list-nav-test.js#L33

**Comment by dwickern** [comment]
OK, I am done with my changes. Besides not highlighting mixed hbs+html, this seems to work very well. This would be a nice improvement for ember users.

**Comment by denofevil** [comment]
@dwickern thank you!
Looks like latest commit is a little bit too aggressive - it enables handlebars typed handler for all injected languages. I think you can check file.getLanguage() instead (cc: @anstarovoyt)
BTW, would you be so kind to sign a [CLA](https://www.jetbrains.com/agreements/cla/)?

**Comment by dwickern** [comment]
No problem, I updated the PR and signed your CLA

**Comment by denofevil** [comment]
Thank you for the contribution!

**Comment by anstarovoyt** [comment]
@dwickern Hi. I had to revert the commit 43dfc9135e60f2d0a9cc27a0130ee16b651dc76e because of broken tests com.dmarcotte.handlebars.format.HbFormatterSampleFileTest . Could you take a look?

**Pull request merged**
